include-file = ~/.config/polybar/system.ini

[module-base]
format-background = ${colors.base}
format-padding = 0
format-margin = 0

[module/date]
type = internal/date
inherit = module-base
interval = 1
date = %d
label ="%date%"
label-foreground = ${colors.foreground}
format-prefix-foreground = ${colors.foreground}
format-background = ${colors.background-alt}
format-prefix = "  "

[module/time]
inherit = module-base
type = internal/date
interval = 30
format-background = ${colors.background-alt}
date =%H:%M
format-prefix = "  "
format-prefix-foreground = ${colors.foreground}
label-foreground = ${colors.foreground}
label = "%date%"

[module/blt]
type = custom/script
exec = ~/.config/polybar/sblt
format-foreground     = ${colors.blue}
click-left = opdrofi
interval = 1

[module/xkeyboard]
type = internal/xkeyboard

blacklist-0 = num lock
blacklist-1 = scroll lock

;format-foreground     = ${colors.foreground-alt}
format-prefix         = 
format-prefix-padding = 1
label-layout          = %layout%
label-layout-padding  = 1

label-indicator-foreground = ${colors.alert}
label-indicator-padding    = 1

[module/memory]
type              = custom/script
exec              = ~/.config/polybar/scripts/memory.sh
format-foreground = ${colors.pink}
interval          = 1
; click-left = kitty -e htop

[module/network]
type      = internal/network
; Interface
interface-type  = wireless
interface       = ${system.network_interface_wireless}
; Disconnected.
format-disconnected                   = <label-disconnected>
label-disconnected                    = "Offline"
format-disconnected-prefix            = "󰤭  "
format-disconnected-prefix-foreground = ${colors.yellow}
format-disconnected-background        = ${colors.base}
format-disconnected-foreground        = ${colors.yellow}
; Connected
label-connected             = "%essid% "
format-connected            = <ramp-signal> <label-connected>
format-connected-background = ${colors.base}
format-connected-foreground = ${colors.yellow}
ramp-signal-foreground      = ${colors.yellow}
ramp-signal-0               = "󰤯 "
ramp-signal-1               = "󰤟 "
ramp-signal-2               = "󰤢 "
ramp-signal-3               = "󰤢 "
ramp-signal-4               = "󰤨 "
ramp-signal-5               = "󰤨 "
ramp-signal-6               = "󰤨 "
; Packet loss.
format-packetloss                 = <animation-packetloss> <label-connected>
animation-packetloss-0            = " "
animation-packetloss-0-foreground = ${colors.yellow}
animation-packetloss-1            = " "
animation-packetloss-1-foreground = ${colors.yellow}
; Framerate in milliseconds
animation-packetloss-framerate = 500

[module/battery]
; Settings.
inherit=module-base
type=internal/battery
full-at=100
battery=${system.battery}
adapter=${system.adapter}
poll-interval=30
time-format=%H:%M

; Charging.
format-charging=<animation-charging><bar-capacity>
label-charging-background=${colors.background}
label-charging-foreground=${colors.foreground}
; Charging animation!
animation-charging-0="  "
animation-charging-1="  "
animation-charging-2="  "
animation-charging-3="  "
animation-charging-4="  "
animation-charging-foreground=${colors.yellow}
animation-charging-background=${colors.background}
animation-charging-framerate=750

; Full.
label-full="  "
format-full=<label-full><bar-capacity>
label-full-background=${colors.background}
label-full-foreground=${colors.green}

; Discharging.
label-discharging="  "
format-discharging=<ramp-capacity><bar-capacity>
label-discharging-background=${colors.background}
label-discharging-foreground=${colors.yellow}

; Bar.
bar-capacity-format = %fill%%empty%
bar-capacity-width = 10
bar-capacity-gradient = true
bar-capacity-indicator = "—"
bar-capacity-fill = "━"
bar-capacity-empty = "━"
bar-capacity-empty-background= ${colors.background}
bar-capacity-indicator-background= ${colors.background}
bar-capacity-fill-background= ${colors.background}
bar-capacity-empty-foreground = ${colors.gray2}
bar-capacity-fill-foreground = ${colors.green}
format-bar-capacity-background = ${colors.background}
; Must use the non antialiased font here.
bar-capacity-fill-font = 3
bar-capacity-empty-font = 3

;         
; Have these here so that the bottom 40% can have changed colors.
ramp-capacity-0 = "  "
ramp-capacity-1 = "  "
ramp-capacity-2 = "  "
ramp-capacity-3 = "  "
ramp-capacity-4 = "  "
ramp-capacity-5 = "  "
ramp-capacity-6 = "  "
ramp-capacity-7 = "  "
ramp-capacity-8 = "  "
ramp-capacity-9 = "  "
ramp-capacity-foreground=${colors.yellow}
ramp-capacity-background=${colors.background}
ramp-capacity-0-foreground = ${colors.red}
ramp-capacity-1-foreground = ${colors.red}
ramp-capacity-2-foreground = ${colors.orange}
ramp-capacity-3-foreground = ${colors.orange}
